In [1]:
import pandas as pd

df = pd.read_csv("../data/mental_health_combined.csv")

FileNotFoundError: [Errno 2] No such file or directory: '../data/mental_health_combined.csv'

In [2]:
import os
os.getcwd()

'c:\\Users\\HP\\Desktop\\AI EXAM ANXIETY DETECTOR\\notebooks'

In [3]:
os.listdir()

['01_dataset_inspection.ipynb']

In [4]:
import os
os.listdir("..")

['-$ Exam Anxiety Detector Document.docx',
 '.git',
 '.gitignore',
 'AI Exam Anxiety Detector Document.docx',
 'backend',
 'data',
 'Extra',
 'frontend',
 'model',
 'notebooks',
 'requirements.txt',
 'src',
 'venv']

In [5]:
import pandas as pd

df = pd.read_csv("../data/mental_health_combined.csv")

FileNotFoundError: [Errno 2] No such file or directory: '../data/mental_health_combined.csv'

In [6]:
import os

print(os.listdir("../data"))

['mental_health_combined_test.csv']

In [8]:
import pandas as pd

df = pd.read_csv("../data/mental_health_combined_test.csv")

In [9]:
df.head()

                                                text   status
0  i don't understand whats wrong with me. i don'...  Anxiety
1  usually when i have anxiety just chatting with...  Anxiety
2  well, i've had anxiety and panic syndrome for ...  Anxiety
3  for the most minimal of things, like standing ...  Anxiety
4  i stay away from family and live with my roomm...  Anxiety

In [10]:
df.shape

(992, 2)

In [11]:
df.columns

Index(['text', 'status'], dtype='object')

In [12]:
df.isnull().sum()

text      0
status    0
dtype: int64

In [13]:
df['status'].value_counts()

status
Anxiety       248
Depression    248
Normal        248
Suicidal      248
Name: count, dtype: int64

### Label Encoding for Machine Learning

Machine learning models require numerical labels rather than text.  
We map the original mental-health categories to numerical anxiety levels:

- 0 → Low Anxiety  
- 1 → Moderate Anxiety  
- 2 → High Anxiety

This ensures the model can process the labels correctly during training.

In [1]:
# Define label mapping from text to numerical anxiety levels
label_mapping = {
    'Normal': 0,
    'Stress': 1,
    'Anxiety': 1,
    'Depression': 2,
    'Suicidal': 2,
    'Bipolar': 2,
    'Personality disorder': 2
}

# Apply mapping to create a new column 'anxiety_level'
df['anxiety_level'] = df['status'].map(label_mapping)

# Check the first few rows to verify
df.head()

NameError: name 'df' is not defined

In [2]:
import os
os.listdir("../data")

['mental_health_combined_test.csv']

In [3]:
import pandas as pd

df = pd.read_csv("../data/mental_health_combined_test.csv")
print("Dataset loaded! Shape:", df.shape)

Dataset loaded! Shape: (992, 2)

In [4]:
label_mapping = {
    'Normal': 0,
    'Stress': 1,
    'Anxiety': 1,
    'Depression': 2,
    'Suicidal': 2,
    'Bipolar': 2,
    'Personality disorder': 2
}

df['anxiety_level'] = df['status'].map(label_mapping)
df.head()

                                                text   status  anxiety_level
0  i don't understand whats wrong with me. i don'...  Anxiety              1
1  usually when i have anxiety just chatting with...  Anxiety              1
2  well, i've had anxiety and panic syndrome for ...  Anxiety              1
3  for the most minimal of things, like standing ...  Anxiety              1
4  i stay away from family and live with my roomm...  Anxiety              1

In [5]:
df['anxiety_level'].isnull().sum()

np.int64(0)

In [6]:
df['anxiety_level'].value_counts()

anxiety_level
2    496
1    248
0    248
Name: count, dtype: int64